# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import facenet_pb2 as facenet__pb2


class FaceNetStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GenerateEmbedding = channel.unary_unary(
        '/facenet_server.FaceNet/GenerateEmbedding',
        request_serializer=facenet__pb2.EmbeddingRequest.SerializeToString,
        response_deserializer=facenet__pb2.EmbeddingReply.FromString,
        )


class FaceNetServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GenerateEmbedding(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FaceNetServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GenerateEmbedding': grpc.unary_unary_rpc_method_handler(
          servicer.GenerateEmbedding,
          request_deserializer=facenet__pb2.EmbeddingRequest.FromString,
          response_serializer=facenet__pb2.EmbeddingReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'facenet_server.FaceNet', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
