# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: facenet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='facenet.proto',
  package='facenet_server',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rfacenet.proto\x12\x0e\x66\x61\x63\x65net_server\"(\n\x10\x45mbeddingRequest\x12\x14\n\x0cimage_base64\x18\x01 \x01(\t\",\n\x0e\x45mbeddingReply\x12\r\n\x05\x65rror\x18\x01 \x01(\x05\x12\x0b\n\x03\x64im\x18\x02 \x03(\x01\x32\x62\n\x07\x46\x61\x63\x65Net\x12W\n\x11GenerateEmbedding\x12 .facenet_server.EmbeddingRequest\x1a\x1e.facenet_server.EmbeddingReply\"\x00\x62\x06proto3')
)




_EMBEDDINGREQUEST = _descriptor.Descriptor(
  name='EmbeddingRequest',
  full_name='facenet_server.EmbeddingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_base64', full_name='facenet_server.EmbeddingRequest.image_base64', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=73,
)


_EMBEDDINGREPLY = _descriptor.Descriptor(
  name='EmbeddingReply',
  full_name='facenet_server.EmbeddingReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='facenet_server.EmbeddingReply.error', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dim', full_name='facenet_server.EmbeddingReply.dim', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=119,
)

DESCRIPTOR.message_types_by_name['EmbeddingRequest'] = _EMBEDDINGREQUEST
DESCRIPTOR.message_types_by_name['EmbeddingReply'] = _EMBEDDINGREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmbeddingRequest = _reflection.GeneratedProtocolMessageType('EmbeddingRequest', (_message.Message,), {
  'DESCRIPTOR' : _EMBEDDINGREQUEST,
  '__module__' : 'facenet_pb2'
  # @@protoc_insertion_point(class_scope:facenet_server.EmbeddingRequest)
  })
_sym_db.RegisterMessage(EmbeddingRequest)

EmbeddingReply = _reflection.GeneratedProtocolMessageType('EmbeddingReply', (_message.Message,), {
  'DESCRIPTOR' : _EMBEDDINGREPLY,
  '__module__' : 'facenet_pb2'
  # @@protoc_insertion_point(class_scope:facenet_server.EmbeddingReply)
  })
_sym_db.RegisterMessage(EmbeddingReply)



_FACENET = _descriptor.ServiceDescriptor(
  name='FaceNet',
  full_name='facenet_server.FaceNet',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=121,
  serialized_end=219,
  methods=[
  _descriptor.MethodDescriptor(
    name='GenerateEmbedding',
    full_name='facenet_server.FaceNet.GenerateEmbedding',
    index=0,
    containing_service=None,
    input_type=_EMBEDDINGREQUEST,
    output_type=_EMBEDDINGREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FACENET)

DESCRIPTOR.services_by_name['FaceNet'] = _FACENET

# @@protoc_insertion_point(module_scope)
