// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: facenet.proto
#ifndef GRPC_facenet_2eproto__INCLUDED
#define GRPC_facenet_2eproto__INCLUDED

#include "facenet.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc_impl {
class CompletionQueue;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc_impl

namespace grpc {
namespace experimental {
template <typename RequestT, typename ResponseT>
class MessageAllocator;
}  // namespace experimental
}  // namespace grpc

namespace facenet_server {

class FaceNet final {
 public:
  static constexpr char const* service_full_name() {
    return "facenet_server.FaceNet";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GenerateEmbedding(::grpc::ClientContext* context, const ::facenet_server::EmbeddingRequest& request, ::facenet_server::EmbeddingReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::facenet_server::EmbeddingReply>> AsyncGenerateEmbedding(::grpc::ClientContext* context, const ::facenet_server::EmbeddingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::facenet_server::EmbeddingReply>>(AsyncGenerateEmbeddingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::facenet_server::EmbeddingReply>> PrepareAsyncGenerateEmbedding(::grpc::ClientContext* context, const ::facenet_server::EmbeddingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::facenet_server::EmbeddingReply>>(PrepareAsyncGenerateEmbeddingRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void GenerateEmbedding(::grpc::ClientContext* context, const ::facenet_server::EmbeddingRequest* request, ::facenet_server::EmbeddingReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GenerateEmbedding(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::facenet_server::EmbeddingReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GenerateEmbedding(::grpc::ClientContext* context, const ::facenet_server::EmbeddingRequest* request, ::facenet_server::EmbeddingReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void GenerateEmbedding(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::facenet_server::EmbeddingReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::facenet_server::EmbeddingReply>* AsyncGenerateEmbeddingRaw(::grpc::ClientContext* context, const ::facenet_server::EmbeddingRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::facenet_server::EmbeddingReply>* PrepareAsyncGenerateEmbeddingRaw(::grpc::ClientContext* context, const ::facenet_server::EmbeddingRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status GenerateEmbedding(::grpc::ClientContext* context, const ::facenet_server::EmbeddingRequest& request, ::facenet_server::EmbeddingReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::facenet_server::EmbeddingReply>> AsyncGenerateEmbedding(::grpc::ClientContext* context, const ::facenet_server::EmbeddingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::facenet_server::EmbeddingReply>>(AsyncGenerateEmbeddingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::facenet_server::EmbeddingReply>> PrepareAsyncGenerateEmbedding(::grpc::ClientContext* context, const ::facenet_server::EmbeddingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::facenet_server::EmbeddingReply>>(PrepareAsyncGenerateEmbeddingRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void GenerateEmbedding(::grpc::ClientContext* context, const ::facenet_server::EmbeddingRequest* request, ::facenet_server::EmbeddingReply* response, std::function<void(::grpc::Status)>) override;
      void GenerateEmbedding(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::facenet_server::EmbeddingReply* response, std::function<void(::grpc::Status)>) override;
      void GenerateEmbedding(::grpc::ClientContext* context, const ::facenet_server::EmbeddingRequest* request, ::facenet_server::EmbeddingReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void GenerateEmbedding(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::facenet_server::EmbeddingReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::facenet_server::EmbeddingReply>* AsyncGenerateEmbeddingRaw(::grpc::ClientContext* context, const ::facenet_server::EmbeddingRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::facenet_server::EmbeddingReply>* PrepareAsyncGenerateEmbeddingRaw(::grpc::ClientContext* context, const ::facenet_server::EmbeddingRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GenerateEmbedding_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GenerateEmbedding(::grpc::ServerContext* context, const ::facenet_server::EmbeddingRequest* request, ::facenet_server::EmbeddingReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GenerateEmbedding : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_GenerateEmbedding() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GenerateEmbedding() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GenerateEmbedding(::grpc::ServerContext* context, const ::facenet_server::EmbeddingRequest* request, ::facenet_server::EmbeddingReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGenerateEmbedding(::grpc::ServerContext* context, ::facenet_server::EmbeddingRequest* request, ::grpc::ServerAsyncResponseWriter< ::facenet_server::EmbeddingReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GenerateEmbedding<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GenerateEmbedding : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_GenerateEmbedding() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::facenet_server::EmbeddingRequest, ::facenet_server::EmbeddingReply>(
          [this](::grpc::ServerContext* context,
                 const ::facenet_server::EmbeddingRequest* request,
                 ::facenet_server::EmbeddingReply* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->GenerateEmbedding(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_GenerateEmbedding(
        ::grpc::experimental::MessageAllocator< ::facenet_server::EmbeddingRequest, ::facenet_server::EmbeddingReply>* allocator) {
      static_cast<::grpc::internal::CallbackUnaryHandler< ::facenet_server::EmbeddingRequest, ::facenet_server::EmbeddingReply>*>(
          ::grpc::Service::experimental().GetHandler(0))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_GenerateEmbedding() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GenerateEmbedding(::grpc::ServerContext* context, const ::facenet_server::EmbeddingRequest* request, ::facenet_server::EmbeddingReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void GenerateEmbedding(::grpc::ServerContext* context, const ::facenet_server::EmbeddingRequest* request, ::facenet_server::EmbeddingReply* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_GenerateEmbedding<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GenerateEmbedding : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_GenerateEmbedding() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GenerateEmbedding() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GenerateEmbedding(::grpc::ServerContext* context, const ::facenet_server::EmbeddingRequest* request, ::facenet_server::EmbeddingReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GenerateEmbedding : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_GenerateEmbedding() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GenerateEmbedding() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GenerateEmbedding(::grpc::ServerContext* context, const ::facenet_server::EmbeddingRequest* request, ::facenet_server::EmbeddingReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGenerateEmbedding(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GenerateEmbedding : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_GenerateEmbedding() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->GenerateEmbedding(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_GenerateEmbedding() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GenerateEmbedding(::grpc::ServerContext* context, const ::facenet_server::EmbeddingRequest* request, ::facenet_server::EmbeddingReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void GenerateEmbedding(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GenerateEmbedding : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_GenerateEmbedding() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::facenet_server::EmbeddingRequest, ::facenet_server::EmbeddingReply>(std::bind(&WithStreamedUnaryMethod_GenerateEmbedding<BaseClass>::StreamedGenerateEmbedding, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_GenerateEmbedding() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GenerateEmbedding(::grpc::ServerContext* context, const ::facenet_server::EmbeddingRequest* request, ::facenet_server::EmbeddingReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGenerateEmbedding(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::facenet_server::EmbeddingRequest,::facenet_server::EmbeddingReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GenerateEmbedding<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GenerateEmbedding<Service > StreamedService;
};

}  // namespace facenet_server


#endif  // GRPC_facenet_2eproto__INCLUDED
